import { FC } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import { serialize } from 'next-mdx-remote/serialize';
import { MDXRemote } from 'next-mdx-remote';

const Test: FC = ({ children }) => {
  return <small>{children}</small>;
};

const Home: NextPage<{ source: any }> = ({ source }) => {
  return (
    <>
      <Head>
        <title>Blog it</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Wrapper>
        <MDXRemote {...source} components={{ Test }} />
      </Wrapper>
    </>
  );
};

export default Home;

const Wrapper = styled.section`
  display: inline-flex;
  justify-content: center;
  align-items: center;
  width: 100%;
`;

export async function getStaticProps() {
  try {
    // MDX text - can be from a local file, database, anywhere
    const source = 'Some **mdx** text, <Test> with a component </Test>';
    const mdxSource = await serialize(source);
    return { props: { source: mdxSource } };
  } catch (e: any) {
    console.log('error', e);
  }
}
